q learning 

In [28]:
import numpy as np
R = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100]])

In [29]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [30]:
Q=np.matrix(np.zeros([6,6]))

In [31]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [32]:
gamma=0.8

initial_state=1

In [33]:
def available_actions(state):
  current_state_row=R[state,]
  av_act = np.where(current_state_row>=0)[1]
  return av_act

In [34]:
available_act= available_actions(initial_state)

In [35]:
available_act

array([3, 5])

In [36]:
def sample_next_action(available_actions_range):
  next_action=int(np.random.choice(available_act,1))
  return next_action

In [37]:
action =sample_next_action(available_act)

In [38]:
action

5

In [39]:
def update(current_state,action,gamma):
  max_index=np.where(Q[action,]==np.max(Q[action,]))[1]

  if max_index.shape[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
    max_index=int(max_index)
  max_value=Q[action,max_index]

  Q[current_state,action]=R[current_state,action]+gamma*max_value
  update(initial_state,action,gamma)

In [40]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [43]:
for i in range(100):
    current_state=np.random.randint(0, int(Q.shape[0]))
    available_act=available_actions(current_state)
    action=sample_next_action(available_act)
    update(current_state, action,gamma)


RecursionError: ignored

In [42]:
for i in range (10000):
  current_state=np.random.randint(0,int(Q.shape[0]))
  available_act=available_actions(current_state)
  action=sample_next_action(available_act)
  update(current_state,action,gamma)

print("Trained Q matrix:")
print(Q/np.max(Q)*100)

RecursionError: ignored